#与环境无关的通用配置
spring:
  application:
    name: faxe
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/ffaxe?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    # type: com.alibaba.druid.pool.DruidDataSource

#mybaits
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nuist.faxe.web.domain.

server:
  port: 8080
#  设置https适配
  tomcat:
    protocol-header: x-forwarded-proto
  use-forward-headers: true

# 支持跨域
web.cors:
  enabled: true
  allowCredentials: true
  allowedMeth ods:
    - '*'
  allowedOrigins:
    - '*'
  allowedHeaders:
    - '*'

faxe.file.storage.path: E:\毕设\faxe-ui\upload
faxe.file.out.path: E:\毕设\faxe-ui\out